language: node_js

node_js:
  - "4.2"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots,coverage --browsers=Firefox

after_script: "cat coverage/report-lcov/lcov.info | node_modules/coveralls/bin/coveralls.js"
